spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shopping_cart
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-circular-references: true